module.exports = {
    userRole: ['admin', 'user'],
    roleUser: {
        ADMIN: 'admin',
        USER: 'user',
    },
    userType: ['INDIVIDUAL', 'ORGANIZATION'],
    cultureType: ['international', 'national'],
    vehicleType: ['tractor', 'car'],
    country: ['INDIA', 'UAE', 'USA'],
    parcelStatus: ['pending', 'initiated', 'processing', 'processed'],
    docType: ['PASSPORT', 'DRIVINGLICENSE', 'PANCARD', 'UTILITYBILL'],
    errorMessage: {
        SUCCESS: 'SUCCESS',
        FAILED: 'FAILED',
        ACCESS_DENIED: 'ACCESS_DENIED',
        TOKEN_EXPIRED: 'TOKEN_EXPIRED',
        TOKEN_UNAUTHORIZED: 'TOKEN_UNAUTHORIZED',
        REQUIRED: 'REQUIRED',
        BLOCKED: 'BLOCKED_ACCOUNT',
        EMAIL_NOT_ACTIVATED: 'EMAIL_NOT_ACTIVATED',
        INVALID_PASSWORD: 'INVALID_PASSWORD',
        USER_SUCCESSFULLY_REGISTERED: 'USER_SUCCESSFULLY_REGISTERED',
        LOGGED_IN_SUCCESSFULLY: 'USER_SUCCESSFULLY_LOGGEDIN',
        INVALID_USER_NAME: 'INVALID_USER_NAME',
        INVALID_INPUT_PARAMETERS: 'INVALID_INPUT_PARAMETERS',
        VALIDATION_ERROR: 'VALIDATION_ERROR',
        NOT_FOUND: 'NOT_FOUND',
        FORGOT_PASSWORD: 'FORGOT_PASSWORD',
        CHANGE_PASSWORD: 'PASSWORD_HAS_BEEN_CHANGED_SUCCESSFULLY',
        EMAIL_VERIFIED: 'EMAIL_VERIFIED',
        IMAGE_TYPE_AND_SIZE_ERROR: 'Image not of jpeg, jpg, png or pdf type or size too large',
        OTP_SEND_SUCCESS: 'OTP_SEND_SUCCESS',
        OTP_VERIFIED_SUCCESS: 'OTP_VERIFIED_SUCCESS',
        OTP_VERIFIED_FAIL: 'OTP_VERIFIED_FAIL',
        OTP_SEND_FAIL: 'OTP_SEND_FAIL',
        ALREADY_PRESENT: 'ALREADY_PRESENT',
    },
    emailType: {
        emailVerificationMail: 'sendEmailVerificationMail',
        forgotPasswordMail: 'sendForgotPassword',
        sendPasswordResetCompleted: 'sendPasswordResetCompleted',
        sendEmailActivated: 'sendEmailActivated',
    },
    version: {
        v1: 'v1.0.0',
        v2: 'v2.0.0',
    },
};
